name: tgv_max_alert
description: App to have alert when a TGV MAX seat is available
version: 1.0.0+20190606

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^2.1.16
  intl: ^0.16.0
  shared_preferences: ^0.5.3+4
  flutter_typeahead: ^1.6.1
  flutter_local_notifications: ^0.8.2+1
  uuid: ^2.0.2
  background_fetch: ^0.2.0

dependency_overrides:
  keyboard_visibility:
    git: git://github.com/yoali11/flutter_keyboard_visibility.git

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
